GET http://localhost:2000/pokemon/ditto

###
POST http://localhost:2000/pokemon
Content-Type: application/json

{
    "name": "andres",
    "type": "normaliyo es",
    "clases":[
        {
            "transforma":"bicis"
        }
    ]
}